name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Konfigurowanie JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file demo/pom.xml
    - name: Testuj z Maven
      run: mvn test --file demo/pom.xml
